apiVersion: apps/v1
kind: Deployment
metadata:
  name: odd-even-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odd-even
  template:
    metadata:
      labels:
        app: odd-even
    spec:
      containers:
      - name: python-container
        image: abdul2108/odd-even:1.0